config/routes.rb
Pro3::Application.routes.draw do
resources :users, :only => [:new, :create, :destroy, :update, :edit, :show, :index] do
     member do
       get :following, :followers
     end
  end   
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  root :to => 'pages#home'

  
  get "users/new"
  get "users/create"
  get "home/index"

  

  match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Acerca de nosotros", about_path %></li>
      <li><%= link_to "Contactenos", contact_path %></li>
      <li><a href="http://news.railstutorial.org/" target="_blank">Noticias</a></li>
      <li><a href="http://www.railstutorial.org/" target="_blank">Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, :controller=>'home', :action=>'index' %>
  <nav class="round">
    <ul>
      <% if signed_in? %>
      <li><%= link_to "Micropost", :controller=>'home', :action=>'index' %></li>
      <% else %>
      <li><%= link_to "Home", :controller=>'home', :action=>'index' %></li>
      <% end %>
      <% if signed_in? %>
 	  <li><%= link_to "Usuarios", users_path %></li>
      <li><%= link_to "Perfil", current_user %></li>
	  <li><%= link_to "Editar Perfil", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Ayuda", help_path %></li>
      <% if signed_in? %>
      <h6>Sesión: <%=  current_user.name %> - <%=  current_user.email %></h6>
      <li><%= link_to "Cerrar sesión", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Ingresar", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/_topbar.html.erb
	<div id="top-bar">
		<div class="container">

			<div class="span-16">
				<ul id="top-links-left">
					<li><a href="http://www.ellabullis.org/pages/story"><span>Ella's Story</span></a></li>

					<li><a href="http://www.ellabullis.org/pages/difference"><span>What Makes Us Different</span></a></li>
					<li><a href="http://www.ellabullis.org/pages/team"><span>Our Team &amp; Sponsors</span></a></li>
					<li><a href="http://www.ellabullis.org/news"><span>News</span></a></li>
					<!-- **coming soon!** <li><a href="http://www.ellabullis.org/pages/store"><span>Store</span></a></li> -->
				</ul>
			</div>
                </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>	
	<%= javascript_include_tag :defaults %>
  </head>
  <body class="body round">
     <div class="container round">
	      <%= render 'layouts/header' %>
	      <section id="content" class="round">
			   <% flash.each do |key, value| %>
			        <div class="flash <%= key %>"><%= value %></div>
			   <% end %>
                             <%= yield %>
	      </section>
	 	  <%= render 'layouts/footer' %>
	    </div>
  </body>
</html>